### ISSUE TITLE
Update GitHub Actions: Update `javaOptions`

### ISSUE THREAD

**Issue by kevin-lee** [kevin-lee/refined4s#376]
### Summary

Update GitHub Actions: Update `javaOptions`

### Version

`0.18.0`

### Description

```yml
env:
  GH_SBT_OPTS: "-Xss64m -Xms1024m -Xmx8G -XX:MaxMetaspaceSize=2G -XX:-UseGCOverheadLimit -XX:MaxInlineLevel=18 -XX:+UnlockExperimentalVMOptions"
  GH_JVM_OPTS: "-Xss64m -Xms1024m -Xmx8G -XX:MaxMetaspaceSize=2G -XX:-UseGCOverheadLimit -XX:MaxInlineLevel=18 -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler"
```
